### ISSUE TITLE
A bit confused on this error.

### ISSUE THREAD

**Issue by SirTwsted** [teamauroramods/Fruitful-Fabric#6] opened 2021-07-09 12:05 UTC
I have Fabric API installed and running in CurseForge app to play the game.
MC version is 1.17+  and for some odd reason this is telling me its incompatible with the game. 

![Screenshot_238](https://user-images.githubusercontent.com/15247713/125075276-620d1580-e08c-11eb-8f44-f54e226dc725.png)

**Comment by JustinPlayzz** [comment] 2021-09-21 21:09
I’m gonna close this issue because there isn’t much we can do about it

**Comment by Steven-Baez** [comment] 2021-09-21 21:10
What you meant to say is that we cant reproduce this lol?

**Closed as completed by JustinPlayzz** 2021-09-21 21:09 UTC
Labels: Not reproducible
